### PR TITLE
Do not override PATH variable

### PR DESCRIPTION
**Pull request by bleshik**

### CODE REVIEW

**Comment by mhart** [comment]
@bleshik can you add some comments here on why you're submitting this?

`PATH` is deliberately passed through in case the user wanted to add their own entries in their LambCI env config.

Are you seeing problems of some kind?

**Comment by bleshik** [comment]
Well, in the case when the user does not explicitly set it in his configs, the default PATH value of the lambci docker image will be used. Not sure, if it's an intended behaviour, but I spent 30 min trying to figure out why the heck is my PATH var is not the one I set in my Dockerfile.test:)

**Comment by mhart** [comment]
@bleshik wait, it's not? You should be able to set PATH to whatever you want in Dockerfile.test – that should be executed _after_ the PATH is passed to ECS

**Comment by mhart** [comment]
Wait, hang on, I'm getting confused :-)

**Comment by mhart** [comment]
I thought I was looking at the code that LambCI invokes ECS with... Sorry – will think about this some more, you might be right!

**Comment by mhart** [comment]
Hmmm, yeah, you're right – it's a bit of a hack at the moment... Any ENV variables you set in Dockerfile.test could get overridden on the command line.

I wonder what the best way to handle this is? I want the user to be able to specify env variables in their LambCI config and have them passed through – but obviously don't really want to override ones set in Dockerfile.test

**Comment by mhart** [comment]
I wonder if i should just whitelist any starting with `LAMBCI_` – and possibly those starting with `AWS_` – in case you want to use AWS credentials in your build.

Thoughts?

**Comment by mhart** [comment]
The other option would be to try and parse Dockerfile.test and see which ENV variables are being set! There are two forms of the ENV command, `ENV name value` and `ENV name=value name=value`

**Comment by mhart** [comment]
Ok, @bleshik I've created a patch for this that only passes through variables that aren't specified in Dockerfile.test

This still won't necessarily solve all the problems with this approach – especially if you're wanting env vars from base images.

I'm wondering whether I should remove the env passing altogether in a future version – or change it so you can specify a whitelist of env vars you want to pass through – it would be a breaking change though.

**Comment by bleshik** [comment]
I'd pass only the variables from secretEnv. Anyway, your patch fixes my particular problem. Thanks!

**Pull request closed without merging**
